[package]
name = "Aresius"
version = "0.1.0"
description = "An open-source HTTP interception proxy for web security testing and bug bounty workflows"
authors = ["Soufiane AMIMI"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "aresius_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1.17.0", features = ["v4"] }
url = "2.5.4"
tokio = { version = "1.40", features = ["net", "io-util", "time", "rt-multi-thread", "macros", "process"] }
anyhow = "1.0.100"
rcgen = { version = "0.14.6", features = ["pem", "x509-parser"] }
tokio-rustls = "0.26.4"
rustls = "0.23.35"
rustls-pemfile = "2.2.0"
rustls-native-certs = "0.8.3"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
tauri-plugin-shell = "2.3.5"
flate2 = "1.1.9"
brotli = "8.0.4"
ruzstd = "0.9.0"
httparse = "1.10.1"
